### ISSUE TITLE
.txt

### ISSUE THREAD

**Issue by ghunter717** [astro-pi/python-sense-hat#107] opened 2021-03-08 11:13 UTC
closed

**Comment by rzr** [comment] 2021-03-23 09:35
Please edit or close this ticket , btw is this project still maintained if not it could be xfered to @abandonware org

https://rzr.github.io/rzr-presentations/docs/abandonware

**Closed** 2021-03-23 09:58 UTC

**Comment by bsimmo** [comment] 2021-03-23 10:16
> Please edit or close this ticket , btw is this project still maintained if not it could be xfered to @abandonware org
> 
> https://rzr.github.io/rzr-presentations/docs/abandonware

It can't change much as it is used by the ESA, RPF etc for various AstroPi competitions.
I believe updating the two Pi's with SenseHATs on the ISS isn't so easy and school and groups use a duplicate of that setup.

**Comment by rzr** [comment] 2021-03-23 11:27
ok thx for feedback, I have opened a couple of PR though:
https://github.com/astro-pi/python-sense-hat/pulls/rzr
